app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::resource("odestinations","OdestinationController"); 
Route::resource("omaps","OmapController");
Route::auth();

Route::get('/get_map', 'BaseController@get_map');
Route::get('/get_destinations', 'BaseController@get_destinations');

Route::get('/', array('as' => 'odestinations.index', 'uses' => 'OdestinationController@index'));

app/Odestination.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Odestination extends Model
{
    //
}

app/Http/Controllers/OdestinationController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Odestination;
use App\Omap;
use Illuminate\Http\Request;
use DB;

class OdestinationController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct()
	{
	    $this->middleware('auth');
	}
	
	
	public function index()
	{
		//$odestinations = Odestination::orderBy('id', 'desc')->paginate(10);
		$tab = "destinations";
		
		$odestinations = DB::select("SELECT d.*, m.title as map_title FROM odestinations d inner join omaps m on m.id = d.omap_id");
		
		return view('odestinations.index', compact('odestinations','tab'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$tab = "destinations";
		$maps = Omap::orderBy('id', 'desc')->get();
		return view('odestinations.create',compact('tab','maps'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$odestination = new Odestination();

		$odestination->omap_id = $request->input("omap_id");
        $odestination->x = $request->input("x");
        $odestination->y = $request->input("y");
        $odestination->z = $request->input("z");
        $odestination->title = $request->input("title");
        $odestination->url = $request->input("url");

		$odestination->save();

		return redirect()->route('odestinations.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$odestination = Odestination::findOrFail($id);
		$tab = "destinations";
		return view('odestinations.show', compact('odestination','tab'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$maps = Omap::orderBy('id', 'desc')->get();
		$odestination = Odestination::findOrFail($id);
		$tab = "destinations";
		return view('odestinations.edit', compact('odestination','tab','maps'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$odestination = Odestination::findOrFail($id);

		$odestination->omap_id = $request->input("omap_id");
        $odestination->x = $request->input("x");
        $odestination->y = $request->input("y");
        $odestination->z = $request->input("z");
        $odestination->title = $request->input("title");
        $odestination->url = $request->input("url");

		$odestination->save();

		return redirect()->route('odestinations.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$odestination = Odestination::findOrFail($id);
		$odestination->delete();

		return redirect()->route('odestinations.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/odestinations/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Odestinations / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('odestinations.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('omap_id')) has-error @endif">
                       
			   		<select name="omap_id" id="omap_id-field" class="form-control">
						@foreach($maps as $map)
			   			<option value="{{$map->id}}">{{$map->title}}</option>
						@endforeach
			   		</select>
					   
                    </div>
                    <div class="form-group @if($errors->has('x')) has-error @endif">
                       <label for="x-field">X</label>
                    <input type="text" id="x-field" name="x" class="form-control" value="{{ old("x") }}"/>
                       @if($errors->has("x"))
                        <span class="help-block">{{ $errors->first("x") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('y')) has-error @endif">
                       <label for="y-field">Y</label>
                    <input type="text" id="y-field" name="y" class="form-control" value="{{ old("y") }}"/>
                       @if($errors->has("y"))
                        <span class="help-block">{{ $errors->first("y") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('z')) has-error @endif">
                       <label for="z-field">Z</label>
                    <input type="text" id="z-field" name="z" class="form-control" value="{{ old("z") }}"/>
                       @if($errors->has("z"))
                        <span class="help-block">{{ $errors->first("z") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('url')) has-error @endif">
                       <label for="url-field">Url</label>
                    <textarea class="form-control" id="url-field" rows="3" name="url">{{ old("url") }}</textarea>
                       @if($errors->has("url"))
                        <span class="help-block">{{ $errors->first("url") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('odestinations.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/odestinations/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i>Editar / Destino #{{$odestination->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('odestinations.update', $odestination->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('omap_id')) has-error @endif">
		
                    <select name="omap_id" id="omap_id-field" class="form-control">
					@foreach($maps as $map)
		   			<option value="{{$map->id}}" @if($odestination->omap_id == $map->id) selected="selected" @endif>{{$map->title}}</option>
					@endforeach
					</select>
					   
                    </div>
                    <div class="form-group @if($errors->has('x')) has-error @endif">
                       <label for="x-field">X</label>
                    <input type="text" id="x-field" name="x" class="form-control" value="{{ is_null(old("x")) ? $odestination->x : old("x") }}"/>
                       @if($errors->has("x"))
                        <span class="help-block">{{ $errors->first("x") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('y')) has-error @endif">
                       <label for="y-field">Y</label>
                    <input type="text" id="y-field" name="y" class="form-control" value="{{ is_null(old("y")) ? $odestination->y : old("y") }}"/>
                       @if($errors->has("y"))
                        <span class="help-block">{{ $errors->first("y") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('z')) has-error @endif">
                       <label for="z-field">Z</label>
                    <input type="text" id="z-field" name="z" class="form-control" value="{{ is_null(old("z")) ? $odestination->z : old("z") }}"/>
                       @if($errors->has("z"))
                        <span class="help-block">{{ $errors->first("z") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ is_null(old("title")) ? $odestination->title : old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('url')) has-error @endif">
                       <label for="url-field">Url</label>
                    <textarea class="form-control" id="url-field" rows="3" name="url">{{ is_null(old("url")) ? $odestination->url : old("url") }}</textarea>
                       @if($errors->has("url"))
                        <span class="help-block">{{ $errors->first("url") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('odestinations.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/odestinations/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>Destinos
            <a class="btn btn-success pull-right" href="{{ route('odestinations.create') }}" style="background: #F3A699; border; border-color: #F3A699;"><i class="glyphicon glyphicon-plus"></i> Crear destino</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
           
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Mapa</th>
                        <th>X</th>
                        <th>Y</th>
                        <th>Z</th>
                        <th>Titulo</th>
                        <th>URL</th>
                            <th class="text-right">Opciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($odestinations as $odestination)
                            <tr>
                                <td>{{$odestination->id}}</td>
                                <td>{{$odestination->map_title}}</td>
                    <td>{{$odestination->x}}</td>
                    <td>{{$odestination->y}}</td>
                    <td>{{$odestination->z}}</td>
                    <td>{{$odestination->title}}</td>
                    <td>{{$odestination->url}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('odestinations.show', $odestination->id) }}" style="background: #F3A699; border; border-color: #F3A699;"> Ver</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('odestinations.edit', $odestination->id) }}" style="background: #F3A699; border; border-color: #F3A699;">Editar</a>
                                    <form action="{{ route('odestinations.destroy', $odestination->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger">Borrar</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                
           

        </div>
    </div>

@endsection

resources/views/odestinations/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Odestinations / Show #{{$odestination->id}}</h1>
        <form action="{{ route('odestinations.destroy', $odestination->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('odestinations.edit', $odestination->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="omap_id">OMAP_ID</label>
                     <p class="form-control-static">{{$odestination->omap_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="x">X</label>
                     <p class="form-control-static">{{$odestination->x}}</p>
                </div>
                    <div class="form-group">
                     <label for="y">Y</label>
                     <p class="form-control-static">{{$odestination->y}}</p>
                </div>
                    <div class="form-group">
                     <label for="z">Z</label>
                     <p class="form-control-static">{{$odestination->z}}</p>
                </div>
                    <div class="form-group">
                     <label for="title">TITLE</label>
                     <p class="form-control-static">{{$odestination->title}}</p>
                </div>
                    <div class="form-group">
                     <label for="url">URL</label>
                     <p class="form-control-static">{{$odestination->url}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('odestinations.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection