app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::resource("odestinations","OdestinationController"); 
Route::resource("omaps","OmapController");
Route::auth();

Route::get('/get_map', 'BaseController@get_map');
Route::get('/get_destinations', 'BaseController@get_destinations');

Route::get('/', array('as' => 'odestinations.index', 'uses' => 'OdestinationController@index'));

app/Omap.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Omap extends Model
{
    //
}

app/Http/Controllers/OmapController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Omap;
use Illuminate\Http\Request;

class OmapController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct()
	{
	    $this->middleware('auth');
	}
	
	public function index()
	{
		$omaps = Omap::orderBy('id', 'desc')->paginate(10);
		$tab = "maps";
		return view('omaps.index', compact('omaps','tab'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$tab = "maps";
		return view('omaps.create',compact('tab'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$omap = new Omap();
        $omap->title = $request->input("title");
		
		if ($request->file('filem')) {
		
			$file = $request->file('filem');
	        // SET UPLOAD PATH
	        $destinationPath = "maps";
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
			$fileName_solo = md5(uniqid(rand(), true));
	        $fileName = $fileName_solo . '.' . $extension;
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$omap->image =  $fileName;
		}
		
		$omap->save();
		return redirect()->route('omaps.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$omap = Omap::findOrFail($id);
		$tab = "maps";
		return view('omaps.show', compact('omap','tab'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$omap = Omap::findOrFail($id);
		$tab = "maps";
		return view('omaps.edit', compact('omap','tab'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$omap = Omap::findOrFail($id);
        $omap->title = $request->input("title");
		
		if ($request->file('filem')) {
		
			$file = $request->file('filem');
	        // SET UPLOAD PATH
	        $destinationPath = "maps";
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
			$fileName_solo = md5(uniqid(rand(), true));
	        $fileName = $fileName_solo . '.' . $extension;
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$omap->image =  $fileName;
		}

		$omap->save();

		return redirect()->route('omaps.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$omap = Omap::findOrFail($id);
		$omap->delete();

		return redirect()->route('omaps.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/omaps/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Omaps / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('omaps.store') }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('image')) has-error @endif">
                       <label for="image-field">Image</label>
                    
						<input type="file" id="filem" name="filem">
					
                    </div>
                    <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('omaps.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/omaps/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i>Editar / Mapa #{{$omap->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('omaps.update', $omap->id) }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('image')) has-error @endif">
                       
					@if($omap->image)
					
						<img class="img-responsive" src="/maps/{{$omap->image}}">
					
					@endif
					
					<input type="file" id="filem" name="filem">
					
                    </div>
                    <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Titulo</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ is_null(old("title")) ? $omap->title : old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('omaps.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/omaps/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>Mapas
           <a class="btn btn-success pull-right" href="{{ route('omaps.create') }}" style="background: #F3A699; border; border-color: #F3A699;"><i class="glyphicon glyphicon-plus"></i> Crear mapa</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($omaps->count())
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width: 5%">Id</th>
							<th style="width: 10%">Titulo</th>
                            <th style="width: 70%">Imágen</th>
                            <th style="width: 15%" class="text-right">Opciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($omaps as $omap)
                            <tr>
                                <td class="col-1" >{{$omap->id}}</td>
                                
                    <td class="col-3">{{$omap->title}}</td>
					<td class="col-5"><img class="img-responsive" src="/maps/{{$omap->image}}"></td>
                                <td class="col-3" class="text-right">
                                    <a class="btn btn-xs btn-primary" style="background: #F3A699; border; border-color: #F3A699;" href="{{ route('omaps.show', $omap->id) }}">Ver</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('omaps.edit', $omap->id) }}" style="background: #F3A699; border; border-color: #F3A699;">Editar</a>
                                    <form action="{{ route('omaps.destroy', $omap->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger" >Borrar</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $omaps->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/omaps/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Omaps / Show #{{$omap->id}}</h1>
        <form action="{{ route('omaps.destroy', $omap->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('omaps.edit', $omap->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="image">IMAGE</label>
                     <p class="form-control-static">{{$omap->image}}</p>
                </div>
                    <div class="form-group">
                     <label for="title">TITLE</label>
                     <p class="form-control-static">{{$omap->title}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('omaps.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection